// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgCmj2e1vU7RflrEo0qCRtPfdpMpua628',
    appId: '1:1005963548127:web:241d63fc22b7ebc43ea06a',
    messagingSenderId: '1005963548127',
    projectId: 'smart-home-app-a72a6',
    authDomain: 'smart-home-app-a72a6.firebaseapp.com',
    storageBucket: 'smart-home-app-a72a6.firebasestorage.app',
    measurementId: 'G-G4BZ56MT1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRKJ6FDtNMFyBeF6RVqxgQs1qgTSBPS9M',
    appId: '1:1005963548127:android:27b93ba9739473fd3ea06a',
    messagingSenderId: '1005963548127',
    projectId: 'smart-home-app-a72a6',
    storageBucket: 'smart-home-app-a72a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8ekKk6rLKN_9jvQ7w7sD-KJh2yzxEefs',
    appId: '1:1005963548127:ios:4c6de733b694510a3ea06a',
    messagingSenderId: '1005963548127',
    projectId: 'smart-home-app-a72a6',
    storageBucket: 'smart-home-app-a72a6.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8ekKk6rLKN_9jvQ7w7sD-KJh2yzxEefs',
    appId: '1:1005963548127:ios:4c6de733b694510a3ea06a',
    messagingSenderId: '1005963548127',
    projectId: 'smart-home-app-a72a6',
    storageBucket: 'smart-home-app-a72a6.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgCmj2e1vU7RflrEo0qCRtPfdpMpua628',
    appId: '1:1005963548127:web:3916bed761d95fcd3ea06a',
    messagingSenderId: '1005963548127',
    projectId: 'smart-home-app-a72a6',
    authDomain: 'smart-home-app-a72a6.firebaseapp.com',
    storageBucket: 'smart-home-app-a72a6.firebasestorage.app',
    measurementId: 'G-683481PD0Q',
  );
}
